### PR TITLE
Working draft of PSC003, YAML metadata, GitHub discussions, automate JSON conversion, organizational changes

### LINKED ISSUE #13: Proposal: Integrate PokePaste's syntax as a PSC standard
The original [Pokémon Standards Initiative](https://www.smogon.com/forums/threads/pok%C3%A9mon-standards-initiative.78201/) started off trying to standardize on syntax for IVs/EVs. Since then, [PokePastes](https://pokepast.es/) have become the de-facto standard across the grassroots VGC scene, and seem to have everything that was desired then.

Here's an example PokePaste, from [https://pokepast.es/6314d9d7554e9f59](https://pokepast.es/6314d9d7554e9f59):

```
Tyranitar @ Weakness Policy  
Ability: Sand Stream  
Level: 50  
Shiny: Yes  
EVs: 236 HP / 132 Atk / 84 Def / 20 SpD / 36 Spe  
Adamant Nature  
- Rock Slide  
- Superpower  
- Lash Out  
- Protect  

Tapu Koko @ Shuca Berry  
Ability: Electric Surge  
Level: 50  
Shiny: Yes  
EVs: 236 HP / 12 Def / 92 SpA / 60 SpD / 108 Spe  
Timid Nature  
IVs: 0 Atk  
- Electroweb  
- Dazzling Gleam  
- Volt Switch  
- Protect  

Kartana @ Assault Vest  
Ability: Beast Boost  
Level: 50  
EVs: 116 HP / 4 Atk / 28 Def / 228 SpD / 132 Spe  
Careful Nature  
- Leaf Blade  
- Sacred Sword  
- Smart Strike  
- Aerial Ace  

Landorus-Therian (M) @ Choice Scarf  
Ability: Intimidate  
Level: 50  
EVs: 36 HP / 196 Atk / 4 Def / 20 SpD / 252 Spe  
Adamant Nature  
- Earthquake  
- Superpower  
- Rock Slide  
- U-turn  

Rotom-Heat @ Safety Goggles  
Ability: Levitate  
Level: 50  
EVs: 244 HP / 12 Def / 116 SpA / 4 SpD / 132 Spe  
Modest Nature  
IVs: 0 Atk  
- Overheat  
- Thunderbolt  
- Nasty Plot  
- Protect  

Gastrodon @ Sitrus Berry  
Ability: Storm Drain  
Level: 50  
EVs: 236 HP / 116 Def / 60 SpA / 84 SpD / 12 Spe  
Modest Nature  
IVs: 0 Atk  
- Ice Beam  
- Earth Power  
- Acid Armor  
- Recover
```

Full syntax is available at [https://pokepast.es/syntax.html](https://pokepast.es/syntax.html).

Please comment any concerns you may have with utilizing PokePaste's syntax as a standard.

### LINKED ISSUE #15: Proposal: Use YAML metadata
Presently, drafts have a special header and are put in the `drafts/` folder, while final documents have a normal header and are put in the `final/` header. Instead of keeping two copies of each document, I propose we simply use YAML metadata at the beginning of the file to keep track of the (a) identifier of the document, (b) the title of the document, (c) the status of the document (final or draft), and (d) the version of the document (array of three integers: major, minor, patch). We may then leave the header as it would appear in the final version even in drafts.

For instance:

```markdown
---
name: Identification of card expansions
identifier: 001

status: draft
version: [0, 0, 1]
---

# PSC 001: Identification of card expansions

...
```

### LINKED ISSUE #16: Proposal: Move proposals to GitHub discussions
GitHub Discussions are much better suited for proposals, with boards to hierarchically sort posts (e.x. an "Announcements" board, a "New Standards" board, a "Miscellaneous" board, etc). Issues can then be used for revisions to existing proposals, so we can have a "PSC 001" tag, a "PSC 002" tag, etc (like we already have, except the Proposal tag can be removed).

### PR DESCRIPTION
**Pull request by kuizeo**
- add working draft of psc003 (fixes #13)
- use yaml metadata (fixes #15)
- reference github discussions in the readme (fixes #16)
- add script to convert standards (`docs`, now in `spec`) to JSON (`data`) &mdash; `tool/spec2json.py`
- rewrite README (TODO: autogenerate spec list)
- move a bunch of files
  - drafts/` and `final/` => YAML metadata
  - `docs` => `spec`
  - meta repository => `meta`

### CODE REVIEW

**Comment by immewnity** [comment]
As this is a fairly major restructure, I'd like to put out a call for additional comments before merging.

**Comment by Dillonzer** [comment]
In the `TODO: autogenerate spec list` can we look into utilizing [shield.io](https://shields.io/category/other)? So we could create things like the following? Other than that I'm happy with the structure change. Shield.io is super easy to use and make custom badges for.

Rejected
Drafts
Approved

**Comment by kuizeo** [comment]
@Dillonzer kinda. in #15 @immewnity stated he wanted an easy way to tell if a given spec was a draft or not, and this doesn't quite do it. I definitely believe this would be a great thing to add, just it might not fix the issue

**Comment by immewnity** [comment]
I'm going to close this as there are too many changes to merge in right now (and I don't know how to use cherry-pick enough to confidently merge bits-and-piece that way). Will take a look at this and Noel's PSC 003 draft and get something merged in for that, at least.

**Pull request closed without merging**
